### ISSUE TITLE
Is the latest release infected?

### ISSUE THREAD

**Issue by ptnapivoski** [w3lh/w3l#11]
[VirusTotal](https://www.virustotal.com/#/file/aea23f3eb452ad76b91cee4e274a6743e2cfcac6a4ab62959d0fbc4204f34711/detection)

**Comment by w3lh** [comment]
Antiviruses doesn't like other process memory manipulation. Their AI often detect 'generic' trojans in such executables. Anyway you could always build loader from source

**Comment by ptnapivoski** [comment]
Thanks.
