### ISSUE TITLE
Add support for 1.28.4

### ISSUE THREAD

**Issue by cen1** [w3lh/w3l#4]
Binary is now renamed, offsets can't be found if renamed to war3.exe.

**Comment by w3lh** [comment]
I don't see any issues with 1.28.4. Filenames just the same as usual. Are you sure in your installation?

**Comment by cen1** [comment]
There is no war3.exe anymore for starters

**Comment by cen1** [comment]
Current loader gives "Could not start War3.exe" since the binary got renamed in this patch

**Comment by w3lh** [comment]
Looks like I had the old war3.exe in Warcraft III directory and it works fine with the old loader btw.
And it seems SRP3 version is broken now. At least I could not login with the new login created on some random pvpgn servers. I would appreciate if someone check the difference

**Comment by w3lh** [comment]
Anyway new common version released

**Comment by cen1** [comment]
Looks good, I was able to login to default config pvpgn. I'll open a seperate issue if I find anything else.
