### ISSUE TITLE
Not backward compatible anymore

### ISSUE THREAD

**Issue by cen1** [w3lh/w3l#5]
W3l right now just fails if it can't open "Warcraft III.exe". It should continue to check for older versions by opening "war3.exe".

This logic should be reworked somehow:
```
if (!CreateProcess(L"Warcraft III.exe", commandline, 0, 0, FALSE, CREATE_SUSPENDED, 0, 0, &startupinfo, &processinfo)) {
	MessageBoxA(0, WAR3_NOT_FOUND_ERR, "Error", MB_OK);
	ExitProcess(2);
}
```

**Comment by w3lh** [comment]
May be, but Warcraft III.exe was present in all older versions of W3, so it shouldn't be an issue

**Comment by cen1** [comment]
Correct but wasn't the old "Warcraft III" strictly a ROC launcher? I'll try it on a pure copy of 1.26

**Comment by w3lh** [comment]
Yes it is. But it still not an issue. Both TFT and ROC have this file.

**Comment by cen1** [comment]
Hmm seems you're correct. I thought it would launch ROC by default but it appears it does not.
