### ISSUE TITLE
1.28.5 support

### ISSUE THREAD

**Issue by cen1** [w3lh/w3l#6]
Patching of Warcraft III.exe fails:
```
Warcraft III.exe:
Read ebx:0xFE9CF000
base: 1380000
[w3l] Trying base offset 0x00061A64 with base 0x01380000...Bad offset
```
if old war3.exe stil exists in the directory it will patch it successfuly but that it a false success (w3 even shows up to date version in old binary, weird).. since versioncheck to pvpgn is the old one.

**Comment by cen1** [comment]
Apparently correct offset is 0x00061A74, also for 1.28.4 (current one is wrong). Find it via ollydbg, it is off by 0x10

**Comment by w3lh** [comment]
For 1.28.4 0x00061A64 looks fine for me:
Warcraft III.exe:
Read ebx:0x00F43000
base: 150000
[w3l] Trying base offset 0x00061A64 with base 0x00150000...Success.
Warcraft III.exe version 1.28.4.7608, size 561 128 bytes

**Comment by cen1** [comment]
Looks like I did a bad clean copy of 1.28.4 and have the wrong Warcraft III.exe in my folder. Anyway, 1.28.5 seems to be correct.
