### ISSUE TITLE
Wine support

### ISSUE THREAD

**Issue by cen1** [w3lh/w3l#7]
I've been digging around what exactly is not working on Wine in recent patches and the first problem appears to be that `GetProcessBaseAddress` is not returning the base address like on Windows. So I tried to get the base address the Winapi way (https://github.com/cen1/w3l/tree/wine-experimental) but I am getting way different addresses:

With NtQueryInformationProcess: ff2be000
With existing ebx hack: 50000

Sources: 
https://stackoverflow.com/questions/45824396/base-address-and-offset-on-readprocessmemory
https://www.codeproject.com/Articles/19685/Get-Process-Info-with-NtQueryInformationProcess

Ideas welcome.

**Comment by w3lh** [comment]
So, there was no much trouble with Wine before, because it doesn't applied base address randomization. Static offsets works perfectly fine. Anything changes? May be current offsets are calculated in wrong way?

**Comment by cen1** [comment]
Not sure this has anything with ASLR. I am just trying to make it work exactly like on windows and base address not working is the first thing I noticed.

However, it appears what I am reading right now is base address of PEB and not base address of the process (https://stackoverflow.com/questions/12808516/pointer-to-baseaddress-through-context-ebx8) so I think I am on to something. Probably just need to do +8 and dereference or read the PEB into a proper struct. I'll play around more over the weekend.

**Comment by LinLo** [comment]
Hello,

I'm still trying to run 1.5.0.1 version with wine on my current warcraft 3 version (1.27a). I just wanted to be sure w3l is working fine before updating to last 1.28 war3 version. 
But it does not work. "There was an error patching war3.exe (Bad offset). Make sure using version 1.22a-128a."
An old w3l version (compiled for test purpose and sent on a forum months ago) continues to work well.

If you want, I can run a "debug" version, like the previous time.

Thanks for your help :)

**Comment by w3lh** [comment]
Hi, LinLo
Getting debug report would be great.

**Comment by LinLo** [comment]
Ok. Could you send me a debug version of the binary ?

**Comment by w3lh** [comment]
Put debug 1.4.0.1 and 1.5.0.1 on wiki

**Comment by cen1** [comment]
Good news, I have a working w3l on linux and I just joined my pvpgn server. Works flawlessly and it was indeed the base address problem. Pull request incoming tomorrow.

**Comment by LinLo** [comment]
Here debug logs with Warcraft 3 1.27a :
http://www14.zippyshare.com/v/N7Jd5naz/file.html

cen1: Thank you ! Also, got an old problem with warcraf3 with wine, maybe you have the same: "After I host the first game, I have to restart the game to host a second one." Is it an internal network problem with wine ?

**Comment by w3lh** [comment]
I checked your logs,  1.27a offset is not applied due to indexing issue. I'll push fix but will wait for cen1's pull request for wine fix to release new version

**Comment by w3lh** [comment]
cen1, could you pls check base address in Wine? Does ASLR applied in Wine? If not, what is static address in 1.27e, 1.27d? I want static patches works too.

**Comment by cen1** [comment]
Base address with this new function on wine is 400000 (tried 4 times). Can't say whether it changes or not. I'll check the older patches soon.

**Comment by w3lh** [comment]
So, that's strange that static offset doesn't work properly in wine, they are also based on 0x400000

**Comment by w3lh** [comment]
LinLo, could you pls verify the latest version from wiki?

**Comment by LinLo** [comment]
Latest version (1.5.1.0) is working very well with 1.27a.
I will soon update to 1.28.x
Thank you very much w3lh and cen1 !

**Comment by cen1** [comment]
Well, afaik it still does 400000+offset but code right now only tries offset directly. Maybe that is the problem?

**Comment by cen1** [comment]
I only have 1.27b with me right now, was that static or already ASLR? I have 1.26 at home but it will have to wait fr the weekend.

**Comment by w3lh** [comment]
So, looks like this issue could be closed?

**Comment by cen1** [comment]
I still need to test older versions. I'll close it myself over the weekend.

**Comment by cen1** [comment]
Looks like loader no longer works for 1.26 but it has nothing to do with my patch, pre-patch build also fails:

```
Warcraft III.exe:
LoadNTDLLFunctions success
NtQueryInformationProcess start
NtQueryInformationProcess success
base winapi: 400000
[w3l] Trying base offset 0x00061A64 with base 0x00400000...Unable to read memory
[w3l] Trying base offset 0x00061A74 with base 0x00400000...Unable to read memory
Read ebx:0x7FFDE000
War3.exe:
base: 400000
[w3l] Trying base offset 0x00060A64 with base 0x00400000...Bad offset
[w3l] Trying base offset 0x0005CA24 with base 0x00400000...Bad offset
[w3l] Trying base offset 0x00056B9C with base 0x00400000...Success.
NXCOMPAT @ 0x0040016F patching failed
NXCOMPAT @ 0x00400177 patching failed
```
this is a bit out of my league

**Comment by w3lh** [comment]
>>[w3l] Trying base offset 0x00056B9C with base 0x00400000...Success
w3l.exe looks fine. 1.26 should use w3lh.dll, is everything ok with that lib?

**Comment by cen1** [comment]
It was my mistake, forgot to copy the proper dll-s. All seems fine.
